# NumPy (Numerical Python)

- Bilimsel hesaplamalar için kullanılır
- Arrayler/ çok boyutlu arrayler ve matrisler üzerinde yüksek performanslı çalışma imkanı sağlar
- Temelleri 1995'te (matrix-sig, Gudio Van Rossum) atılmıştır.
- 2005 yılında Travis Oliphant tarafından hayata geçirilmiştir.
- Listelerle benzerdir, farkı; verimli veri saklama ve vektörel operasyonlardır.
- Sabit tipli veri tutmaya zorlar. Her eleman için ayrı ayrı veri tipini tutmak yerine sadece listenin veri tipini tutar.
- Veri saklama maliyetini düşürür.

### Python list ile Numpy Array Fark Nedir?

Numpy size array oluşturmanın ve içlerindeki sayısal verileri değiştirmenin çok çeşitli hızlı ve verimli yollarını sunar. Bir Python listesi tek bir liste içinde farklı veri türlerini içerebilirken, bir Numpy arraydeki tüm öğeler homojen olmalıdır. Arrayler homojen olmasaydı, arrayler üzerinde gerçekleştirilmesi amaçlanan matematiksel işlemler son derece verimsiz olurdu.


In [1]:
list_x = list(range(10000))

In [2]:
import numpy as np
arr_x = np.array(list_x)

In [3]:
def list_sum():
    total = []
    for i in range(len(list_x)):
        total.append(list_x[i] + list_x[i])
        
def np_arr_sum():
    z = arr_x + arr_x        

In [4]:
from timeit import Timer
t_obj_arr = Timer("np_arr_sum()", "from __main__ import np_arr_sum") 
t_obj_list = Timer("list_sum()", "from __main__ import list_sum") 


print("Python List:", t_obj_list.timeit(1000))
print("Numpy Array:", t_obj_arr.timeit(1000))

Python List: 2.2264902
Numpy Array: 0.006860300000000041


## Numpy Array Oluşturma

Numpy'da dizi oluşturulurken numpy.array fonksiyonu kullanılır.
    
        numpy.array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0, like=None)
 

### Python list ile Numpy Array oluşturma

In [5]:
import numpy as np
py_list = [1,2,3,4,5] 
print(py_list, "type:", type(py_list))
arr = np.array(py_list)
print(arr, "type:", type(arr))

[1, 2, 3, 4, 5] type: <class 'list'>
[1 2 3 4 5] type: <class 'numpy.ndarray'>


In [6]:
py_list = [1,2.0,3.0,4,5] 
print(py_list, "type:", type(py_list))
arr = np.array(py_list)
print(arr, "type:", type(arr))

[1, 2.0, 3.0, 4, 5] type: <class 'list'>
[1. 2. 3. 4. 5.] type: <class 'numpy.ndarray'>


In [7]:
py_list = ["1",2.0,3.0,4,5] 
print(py_list, "type:", type(py_list))
arr = np.array(py_list)
print(arr, "type:", type(arr))

['1', 2.0, 3.0, 4, 5] type: <class 'list'>
['1' '2.0' '3.0' '4' '5'] type: <class 'numpy.ndarray'>


### numpy.arange fonksiyonu ile Array oluşturma

In [8]:
arr = np.arange(20)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

### Ones

In [9]:
# Default olarak float tipinde verileri saklar
# 1 lerden oluşan array oluşrur
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

### Zeros

In [10]:
# İnteger olarak saklamak istiyorsa belirmemiz gerekir
# 0 lardan oluşan array oluşturur
np.zeros((3,3), dtype=int)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

### Full

In [11]:
# Belirtilen sayı ile belirtilen boyutta array oluşturur
x = np.full((3,5), 3)

### Linspace

In [12]:
# Belirtilen aralıkta array oluşturur
np.linspace(0, 1, 10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

### Random

In [13]:
# Normal dağılıma sahip array oluştutur
np.random.normal(10, 4, (3,4))

array([[ 9.37019711, 14.42982464,  7.1862166 , 15.65533854],
       [16.37059356,  2.07926673, 12.03675023,  1.86905826],
       [13.09876457,  8.75008981,  6.09229874,  8.87199146]])

In [14]:
# Belirtilen aralıkta ve eleman sayısında integer değerlerden array oluştutur
np.random.randint(1,10, 10)

array([3, 4, 5, 6, 1, 9, 6, 4, 6, 1])

## Özellikleri

* ndim: boyut sayısı
* shape: boyut bilgisi
* size: toplam eleman sayısı
* dtyoe: veri tipi

In [15]:
arr = np.random.randint(10, size=10)
arr

array([4, 9, 7, 9, 4, 8, 9, 4, 9, 9])

In [16]:
arr.ndim

1

In [17]:
arr.shape

(10,)

In [18]:
arr.size

10

In [19]:
arr.dtype

dtype('int32')

In [20]:
arr1 = np.random.randint(10,  size=(2,2))
arr1

array([[6, 7],
       [5, 7]])

In [21]:
arr1.ndim

2

In [22]:
arr1.shape

(2, 2)

In [23]:
arr1.size

4

In [24]:
arr1.dtype

dtype('int32')

## Append & Delete

In [25]:
arr = np.arange(1,5)
arr

array([1, 2, 3, 4])

In [26]:
## np.append(array_ismi, eklenecek eleman)
arr = np.append(arr, 5)
arr

array([1, 2, 3, 4, 5])

In [27]:
## np.delete(array_ismi, silinecek elemanın indexi)
arr = np.delete(arr, 0)
arr

array([2, 3, 4, 5])

## Reshaping

In [28]:
arr = np.arange(1,21)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [29]:
arr.shape

(20,)

In [30]:
arr = arr.reshape(4,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [31]:
arr.shape

(4, 5)

## Concatenation

In [32]:
x = np.array([1,2,3])
y = np.array([4,5,6])
z = np.array([[1,2,3], 
              [4,5,6]])

In [33]:
# tek boyutlu birleştirme
a1 = np.concatenate([x,y])
a1

array([1, 2, 3, 4, 5, 6])

In [34]:
a1.ndim

1

In [35]:
a1.shape

(6,)

In [36]:
# iki boyutlu satır bazlı birleştirme
a2 = np.concatenate([z,z])
a2

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [37]:
a2.ndim

2

In [38]:
a2.shape

(4, 3)

In [39]:
# iki boyutlu sütun bazlı birleştirme
a2 = np.concatenate([z,z], axis=1)
a2

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [40]:
a2.ndim

2

In [41]:
a2.shape

(2, 6)

## Splitting

In [42]:
x = np.array([1,2,3,4,5,6,7,8,9,10])
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [43]:
np.split(x, [2,6])

[array([1, 2]), array([3, 4, 5, 6]), array([ 7,  8,  9, 10])]

In [44]:
a, b, c = np.split(x, [2,6])

In [45]:
a

array([1, 2])

In [46]:
b

array([3, 4, 5, 6])

In [47]:
c

array([ 7,  8,  9, 10])

In [48]:
m = np.arange(16).reshape(4,4)
m

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [49]:
np.vsplit(m, [1])

[array([[0, 1, 2, 3]]),
 array([[ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [50]:
a, b = np.vsplit(m, [2])

In [51]:
a

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [52]:
b

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [53]:
np.hsplit(m, [1])

[array([[ 0],
        [ 4],
        [ 8],
        [12]]),
 array([[ 1,  2,  3],
        [ 5,  6,  7],
        [ 9, 10, 11],
        [13, 14, 15]])]

In [54]:
c, d = np.hsplit(m, [1])

In [55]:
c

array([[ 0],
       [ 4],
       [ 8],
       [12]])

In [56]:
d

array([[ 1,  2,  3],
       [ 5,  6,  7],
       [ 9, 10, 11],
       [13, 14, 15]])

## Sorting

In [57]:
v = np.array([2,3,5,7,8,5,6,8,9])
v

array([2, 3, 5, 7, 8, 5, 6, 8, 9])

In [58]:
np.sort(v)

array([2, 3, 5, 5, 6, 7, 8, 8, 9])

In [59]:
# iki boyutlu
m = np.random.randint(0, 50, (4,4))
m

array([[ 3, 46, 43,  7],
       [ 7, 41, 39, 35],
       [35, 40, 18, 35],
       [48, 49, 22, 21]])

In [60]:
np.sort(m, axis=0)

array([[ 3, 40, 18,  7],
       [ 7, 41, 22, 21],
       [35, 46, 39, 35],
       [48, 49, 43, 35]])

In [61]:
np.sort(m, axis=1)

array([[ 3,  7, 43, 46],
       [ 7, 35, 39, 41],
       [18, 35, 35, 40],
       [21, 22, 48, 49]])

## Index ile Elemanlara Erişmek

In [62]:
arr = np.random.randint(10, size=10)
arr

array([6, 0, 7, 5, 3, 8, 8, 6, 7, 2])

In [63]:
arr[3]

5

In [64]:
arr[-3]

6

In [65]:
arr[2] = 100
arr

array([  6,   0, 100,   5,   3,   8,   8,   6,   7,   2])

In [66]:
m = np.random.randint(10, size=(3,4))
m

array([[6, 7, 9, 2],
       [4, 8, 4, 0],
       [6, 4, 3, 4]])

In [67]:
m[1,1]

8

In [68]:
m[1,1] = 100
m[1,1]

100

In [69]:
# Integer bir array'e float değer eklediğimiz 
# durumda bu elemanı integer'a dönüştürerek ekler
# Dizi oluşturulurken kullanılan veri tipi sabit kalır
m[1,2] = 3.3
m[1,2]

3

## Slicing ile Elemanlara Erişmek

In [70]:
arr = np.arange(1,30)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [71]:
arr[5:10]

array([ 6,  7,  8,  9, 10])

In [72]:
arr[:6]

array([1, 2, 3, 4, 5, 6])

In [73]:
arr[7:]

array([ 8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24,
       25, 26, 27, 28, 29])

In [74]:
arr[1::5]

array([ 2,  7, 12, 17, 22, 27])

In [75]:
# İki boyutlu slice işlemleri
m = np.random.randint(30, size=(4,7))
m

array([[14, 17, 23, 18, 16, 15, 13],
       [ 7, 25, 16, 21,  1,  6, 29],
       [ 6, 17, 18, 16, 11,  5,  6],
       [13,  8,  1,  6,  6, 14,  9]])

In [76]:
# m[satır, sutün]
m[1:2,:]

array([[ 7, 25, 16, 21,  1,  6, 29]])

In [77]:
m[2:3,:]

array([[ 6, 17, 18, 16, 11,  5,  6]])

In [78]:
m[:,1:2]

array([[17],
       [25],
       [17],
       [ 8]])

In [79]:
m[:,4:]

array([[16, 15, 13],
       [ 1,  6, 29],
       [11,  5,  6],
       [ 6, 14,  9]])

In [80]:
m[1:3, 1:3]

array([[25, 16],
       [17, 18]])

In [81]:
# Alt Küme Üzerinde İşlem Yapmak
arr = np.random.randint(10, size=(5,5))
arr

array([[2, 5, 6, 8, 8],
       [3, 1, 3, 5, 2],
       [2, 4, 2, 9, 2],
       [7, 3, 8, 3, 3],
       [3, 8, 2, 3, 0]])

In [82]:
# Bir arraydan alt küme seçip üzerinde işlem yaptığımızda 
# ana array de bu işlemden etkilenir
arr_alt = arr[0:3,0:3]
arr_alt

array([[2, 5, 6],
       [3, 1, 3],
       [2, 4, 2]])

In [83]:
arr_alt[0,0] = 1000000
arr_alt

array([[1000000,       5,       6],
       [      3,       1,       3],
       [      2,       4,       2]])

In [84]:
arr

array([[1000000,       5,       6,       8,       8],
       [      3,       1,       3,       5,       2],
       [      2,       4,       2,       9,       2],
       [      7,       3,       8,       3,       3],
       [      3,       8,       2,       3,       0]])

In [85]:
# Ana array de değişiklik olmasını istemiyorsak alt kümeyi oluştururken
# copy() fonksiyonunu kullanarak önleyebiliriz

In [86]:
# Bir arraydan alt küme seçip üzerinde işlem yaptığımızda 
# ana array de bu işlemden etkilenir
arr_alt2 = arr[0:3,0:3].copy()
arr_alt2

array([[1000000,       5,       6],
       [      3,       1,       3],
       [      2,       4,       2]])

In [87]:
arr_alt2[0,0] = 11111111
arr_alt2

array([[11111111,        5,        6],
       [       3,        1,        3],
       [       2,        4,        2]])

In [88]:
arr

array([[1000000,       5,       6,       8,       8],
       [      3,       1,       3,       5,       2],
       [      2,       4,       2,       9,       2],
       [      7,       3,       8,       3,       3],
       [      3,       8,       2,       3,       0]])

## Fancy Index ile Elemanlar Erişmek

In [89]:
arr = np.arange(0,100,5)
arr

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80,
       85, 90, 95])

In [90]:
arr[1]

5

In [91]:
arr[3]

15

In [92]:
[arr[2], arr[3]]

[10, 15]

In [93]:
fancy_index = [3,6,9]

In [94]:
arr[fancy_index]

array([15, 30, 45])

In [95]:
m = np.arange(25).reshape(5,5)
m

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [96]:
# m[satır, sütun]
satir = np.array([1,2])
sutun = np.array([3,4])

In [97]:
m[satir, sutun]

array([ 8, 14])

In [98]:
# basit indexle fancy index kullanımı
m[2, [1,2]]

array([11, 12])

In [99]:
# slice indexle fancy index kullanımı
m[0:3, [1,4]]

array([[ 1,  4],
       [ 6,  9],
       [11, 14]])

## Koşullu Eleman İşlemleri

In [100]:
v = np.arange(20)
v

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [101]:
# 7 den küçük elemanlara erişmek için
v < 7 # şart kontrolü yapar

array([ True,  True,  True,  True,  True,  True,  True, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False])

In [102]:
v[v<7] # fancy ile şartı sağlayanları getirir

array([0, 1, 2, 3, 4, 5, 6])

In [103]:
# 7 den küçük ve eşit elemanlar
v[v <= 7]

array([0, 1, 2, 3, 4, 5, 6, 7])

In [104]:
# 7 den büyük elemanlar
v[v > 7]

array([ 8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [105]:
# 7 den büyük ve eşit elemanlar
v[v >= 7]

array([ 7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [106]:
# 7 ye eşit 
v[v == 7]

array([7])

In [107]:
# 7 hariç
v[v != 7]

array([ 0,  1,  2,  3,  4,  5,  6,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

## Matematiksel İşlemler

In [108]:
# Bu işlemler ufunc ile geçekleştirilir
# Hangi işlem gerçekleştirilecekse arka planda 
# o işleme ait fonksiyon çağrılıp işlem yapılır
# np.power(v,2) = v ** 2
# np.add(v,3) = v + 3
v = np.arange(7)
v

array([0, 1, 2, 3, 4, 5, 6])

In [109]:
v + 3

array([3, 4, 5, 6, 7, 8, 9])

In [110]:
np.add(v, 3)

array([3, 4, 5, 6, 7, 8, 9])

In [111]:
v - 2

array([-2, -1,  0,  1,  2,  3,  4])

In [112]:
v * 2

array([ 0,  2,  4,  6,  8, 10, 12])

In [113]:
v / 2

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. ])

In [114]:
v**2

array([ 0,  1,  4,  9, 16, 25, 36], dtype=int32)

In [115]:
v * 10 / 5 - 3

array([-3., -1.,  1.,  3.,  5.,  7.,  9.])

## Numpy ile İki bilinmeyenli Denklem Çözümü

${x_0 + x_1 = 12} \\$
${3 * x_0 + 2 * x_1 = 29}$ 

In [116]:
katsayilar = np.array([[1,1] , [3,2]])
sonuclar = np.array([12,29])

In [117]:
x = np.linalg.solve(katsayilar, sonuclar)
x

array([5., 7.])

-------------------------------------

## Numpy Mülakat Soruları ve Cevapları

#### Numpy Array neden Python listelerden daha iyi?
- Hızlıdır.
- Daha az bellek tükettir.
- Array işlemleri için birçok fonksiyon sunarlar.

#### Standart normal dağılıma sahip 100 elemanlı bir Numpy Array oluşturunuz.

In [118]:
np.random.rand(100)

array([0.51967374, 0.61760661, 0.01864887, 0.25331258, 0.69981069,
       0.70246301, 0.63345954, 0.48109618, 0.95895911, 0.88124833,
       0.38658603, 0.96721123, 0.60948258, 0.06647593, 0.4185175 ,
       0.21530838, 0.62344344, 0.69533967, 0.91571128, 0.43423923,
       0.4654176 , 0.8398562 , 0.70263834, 0.46094304, 0.64357009,
       0.78367798, 0.32963114, 0.62177298, 0.04366656, 0.10320553,
       0.91228378, 0.05102443, 0.43190124, 0.2196026 , 0.68386564,
       0.46749919, 0.55895782, 0.23935935, 0.66720924, 0.78002135,
       0.02399024, 0.46565753, 0.24152107, 0.58233744, 0.19496493,
       0.98936076, 0.8420102 , 0.8047488 , 0.36455119, 0.1188184 ,
       0.97100388, 0.42602667, 0.35025109, 0.60946488, 0.20920399,
       0.35744206, 0.94236823, 0.63063241, 0.68726872, 0.62662116,
       0.04742226, 0.31440875, 0.71863267, 0.71643899, 0.59404121,
       0.3171318 , 0.39029495, 0.97143888, 0.67102168, 0.64862576,
       0.46781964, 0.47043682, 0.14546039, 0.80954447, 0.86524

#### Bir numpy dizisindeki her değerin kaç kez geçtiğini nasıl bulabilirim?

In [119]:
arr = np.array([0, 5, 5, 0, 2, 4, 3, 0, 0, 5, 4, 1, 1, 9, 9])
# 0 dan 4 kez, 1 den 2 kez, 2 den 1 kez...
np.bincount(arr)

array([4, 2, 1, 1, 2, 3, 0, 0, 0, 2], dtype=int64)

#### Numpy'de ravel () işlevi ne işe yarar?

Birden fazla boyuta sahip arrayleri tek boyutlu hale getirir.

In [120]:
x = np.array([[1, 2, 3], [4, 5, 6]])
print(x, "\n")
print(np.ravel(x))

[[1 2 3]
 [4 5 6]] 

[1 2 3 4 5 6]


#### axis = 0 ve axis = 1'nin anlamı nedir?

* axis = 0 satırları(rows) ifade eder.
* axis = 1 sütunları(columns) ifade eder.

#### Numpy nedir ve kullanım alanları nelerdir?

Numpy, Python için bir paket kitaplığıdır ve büyük, çok boyutlu diziler ve matrisler için destek ekleyerek, geniş bir üst düzey matematiksel fonksiyon koleksiyonudur. 

Numpy, 

 * Finansal işlevler
 * Doğrusal Cebir
 * İstatistikler
 * Polinomlar
 * Sıralama ve Arama 

gibi işlemler için Python listelerinin optimize edilmiş bir sürümüdür.

#### Başka bir dizide bulunan öğeleri bir diziden nasıl kaldırabilirim?

In [121]:
a = np.array([5, 4, 3, 2, 1])
b = np.array([4, 8, 9, 10, 1])
np.setdiff1d(a,b) # "a" dizinden "b"dizindeki tüm elemanları kaldırır (iki küme arasındaki fark) 

array([2, 3, 5])

#### Bir Numpy Array'i 2D dizideki belirli bir sütuna göre nasıl sıralayabilirim?

In [122]:
arr = np.array([[1, 2, 3], [4, 5, 6], [0,0,1]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [0, 0, 1]])

In [123]:
arr[:,1].argsort() #Bir diziyi sıralatan indeksleri döndürür.

array([2, 0, 1], dtype=int64)

In [124]:
arr[arr[:,1].argsort()]

array([[0, 0, 1],
       [1, 2, 3],
       [4, 5, 6]])

#### Numpy dizisinin en verimli şekilde ters nasıl alınır?

In [125]:
arr = np.array([9, 10, 1, 2, 0])
reverse_arr = arr[::-1]
reverse_arr

array([ 0,  2,  1, 10,  9])

#### Numpy kullanılırken yüzdelik nasıl hesaplanır?

In [126]:
arr = np.array([11, 22, 33, 44 ,55 ,66, 77])
perc = np.percentile(arr, 40) # Yüzde 40'lık oranı döndürür
print(perc)

37.400000000000006


#### Numpy ile Scipy arasındaki fark nedir?

NumPy, dizi veri türü ve en temel işlemlerden başka hiçbir şey içermez: indeksleme, sıralama, yeniden şekillendirme vb. SciPy'de ise daha fazla işlev bulunur. SciPy, doğrusal cebir modüllerinin daha tam özellikli sürümlerinin yanı sıra diğer birçok sayısal algoritmayı da içerir.

#### Boş bir dizi olup olmadığını kontrol etmenin tercih edilen yolu nedir?

In [127]:
arr = np.zeros((1,0))
print(arr)
arr.size

[]


0

#### Matrices (Matrices) ve Arrays (Diziler) arasındaki fark nedir?

Matrisler yalnızca iki boyutlu olabilir, diziler ise herhangi bir boyuta sahip olabilir.


#### Bir koşulun doğru olduğu bir dizinin indislerini nasıl bulabilirsiniz?

Bir dizi a verildiğinde, arr> 3 koşulu bir boole dizisi döndürür ve False, Python ve NumPy'de 0 olarak yorumlanır.

In [128]:
arr = np.array([[9,8,7],[6,5,4],[3,2,1]])
arr > 3

array([[ True,  True,  True],
       [ True,  True,  True],
       [False, False, False]])

#### Bir dizinin maksimum ve minimum değerlerine nasıl erişiriz?

In [129]:
a = np.arange(10).reshape((2,5))
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [130]:
max_val = np.amax(a)
min_val = np.amin(a)
print(max_val)
print(min_val)

9
0


#### Sütunlar boyunca belirli bir dizinin maksimum ve minimum değerleri arasındaki farkı hesaplamak için bir NumPy programı yazın.

In [131]:
x = np.array([[4, 9, 2, 10],
              [6, 9, 7, 12]])
x

array([[ 4,  9,  2, 10],
       [ 6,  9,  7, 12]])

In [132]:
np.ptp(x, axis=1) # Sütun boyunca değer aralığını (maksimum - minimum) hesaplar.

array([8, 6])

In [133]:
np.ptp(x, axis=0) # Satır boyunca değer aralığını (maksimum - minimum) hesaplar.

array([2, 0, 5, 2])

In [134]:
np.ptp(x) # tüm dizi için değer aralığını hesaplar.

10

#### Numpy da bir dizinin medyanı nasıl bulunur?

In [135]:
arr = np.arange(16).reshape((4, 4))
m = np.median(arr)
m

7.5

#### Sütun boyunca belirli bir dizinin ortalama, standart sapma ve varyansını hesaplamak için bir NumPy programı yazın.

In [136]:
x = np.arange(16)
mean = np.mean(x)
std = np.std(x)
var= np.var(x)
print("Ortalama: {}, Standart Sapma: {}, Varyans: {}".format(mean, std, var))

Ortalama: 7.5, Standart Sapma: 4.6097722286464435, Varyans: 21.25


#### İki numpy dizisi arasındaki kovaryans matrisini hesaplayın.

In [137]:
x = np.array([2, 1, 0])
y = np.array([2, 3, 3])
np.cov(x, y)

array([[ 1.        , -0.5       ],
       [-0.5       ,  0.33333333]])

#### Verilen iki numpy dizisinin Pearson Çarpım Moment Korelasyon Katsayısını hesaplayın

In [138]:
x = np.array([0, 1, 3])
y = np.array([2, 4, 5])
np.corrcoef(x, y)

array([[1.        , 0.92857143],
       [0.92857143, 1.        ]])

#### Histogram hesaplayan bir Numyp programı geliştirin.

In [139]:
nums = np.array([0.5, 0.7, 1.0, 1.2, 1.3, 2.1])
bins = np.array([0, 1, 2, 3])
np.histogram(nums, bins)

(array([2, 3, 1], dtype=int64), array([0, 1, 2, 3]))

#### Bir dizinin elemanların belirtilen dereceden kuvvetini hesaplayın

In [140]:
# der = 3
x = np.arange(7)
np.power(x, 3)

array([  0,   1,   8,  27,  64, 125, 216], dtype=int32)

#### Bir dizinin elemanların belirtilen değere bölümünü hesaplayın

In [141]:
x = np.arange(10)
np.true_divide(x, 3) # / Operatörü, ndarrays üzerinde np.true_divide için bir kısaltma olarak kullanılabilir.

array([0.        , 0.33333333, 0.66666667, 1.        , 1.33333333,
       1.66666667, 2.        , 2.33333333, 2.66666667, 3.        ])

--------------------

### Kaynaklar

#### Websiteleri

- https://numpy.org/learn/
- https://www.linkedin.com/feed/update/urn:li:activity:6783319693840252928/ (Mülakat Sorularının Kaynağı)



#### Kurslar

- https://dphi.tech/courses/introduction-to-numpy/
- https://www.udemy.com/course/python-egitimi/
- https://www.udemy.com/course/herkes-icin-python-programlama/
